// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file order/v1/order_service.proto (package order.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file order/v1/order_service.proto.
 */
export const file_order_v1_order_service: GenFile = /*@__PURE__*/
  fileDesc("ChxvcmRlci92MS9vcmRlcl9zZXJ2aWNlLnByb3RvEghvcmRlci52MSJ+ChJDcmVhdGVPcmRlclJlcXVlc3QSFQoCaWQYASABKAlCCbpIBnIEEAIYMhIuCgpjcmVhdGVkX2F0GAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIhCgVpdGVtcxgDIAMoCzISLm9yZGVyLnYxLkxpbmVJdGVtIkIKCExpbmVJdGVtEhAKCHBvc2l0aW9uGAEgASgFEhIKCnByb2R1Y3RfaWQYAiABKAkSEAoIcXVhbnRpdHkYAyABKAMiFQoTQ3JlYXRlT3JkZXJSZXNwb25zZTJaCgxPcmRlclNlcnZpY2USSgoLQ3JlYXRlT3JkZXISHC5vcmRlci52MS5DcmVhdGVPcmRlclJlcXVlc3QaHS5vcmRlci52MS5DcmVhdGVPcmRlclJlc3BvbnNlQqgBCgxjb20ub3JkZXIudjFCEU9yZGVyU2VydmljZVByb3RvUAFaRGdpdGh1Yi5jb20vQ2hyaXN0aWFuR2FlcnRuZXIvY29ubmVjdC1ycGMtZGVtby9wcm90by9vcmRlci92MTtvcmRlcnYxogIDT1hYqgIIT3JkZXIuVjHKAghPcmRlclxWMeICFE9yZGVyXFYxXEdQQk1ldGFkYXRh6gIJT3JkZXI6OlYxYgZwcm90bzM", [file_buf_validate_validate, file_google_protobuf_timestamp]);

/**
 * @generated from message order.v1.CreateOrderRequest
 */
export type CreateOrderRequest = Message<"order.v1.CreateOrderRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 2;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: repeated order.v1.LineItem items = 3;
   */
  items: LineItem[];
};

/**
 * Describes the message order.v1.CreateOrderRequest.
 * Use `create(CreateOrderRequestSchema)` to create a new message.
 */
export const CreateOrderRequestSchema: GenMessage<CreateOrderRequest> = /*@__PURE__*/
  messageDesc(file_order_v1_order_service, 0);

/**
 * @generated from message order.v1.LineItem
 */
export type LineItem = Message<"order.v1.LineItem"> & {
  /**
   * @generated from field: int32 position = 1;
   */
  position: number;

  /**
   * @generated from field: string product_id = 2;
   */
  productId: string;

  /**
   * @generated from field: int64 quantity = 3;
   */
  quantity: bigint;
};

/**
 * Describes the message order.v1.LineItem.
 * Use `create(LineItemSchema)` to create a new message.
 */
export const LineItemSchema: GenMessage<LineItem> = /*@__PURE__*/
  messageDesc(file_order_v1_order_service, 1);

/**
 * @generated from message order.v1.CreateOrderResponse
 */
export type CreateOrderResponse = Message<"order.v1.CreateOrderResponse"> & {
};

/**
 * Describes the message order.v1.CreateOrderResponse.
 * Use `create(CreateOrderResponseSchema)` to create a new message.
 */
export const CreateOrderResponseSchema: GenMessage<CreateOrderResponse> = /*@__PURE__*/
  messageDesc(file_order_v1_order_service, 2);

/**
 * @generated from service order.v1.OrderService
 */
export const OrderService: GenService<{
  /**
   * @generated from rpc order.v1.OrderService.CreateOrder
   */
  createOrder: {
    methodKind: "unary";
    input: typeof CreateOrderRequestSchema;
    output: typeof CreateOrderResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_order_v1_order_service, 0);

