// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: product/v1/product_service.proto

package productv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_product_v1_product_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_product_v1_product_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_product_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_product_v1_product_service_proto protoreflect.FileDescriptor

const file_product_v1_product_service_proto_rawDesc = "" +
	"\n" +
	" product/v1/product_service.proto\x12\n" +
	"product.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\".\n" +
	"\x11GetProductRequest\x12\x19\n" +
	"\x02id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x182R\x02id\"8\n" +
	"\x12GetProductResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2]\n" +
	"\x0eProductService\x12K\n" +
	"\n" +
	"GetProduct\x12\x1d.product.v1.GetProductRequest\x1a\x1e.product.v1.GetProductResponseB\xb8\x01\n" +
	"\x0ecom.product.v1B\x13ProductServiceProtoP\x01ZHgithub.com/ChristianGaertner/connect-rpc-demo/proto/product/v1;productv1\xa2\x02\x03PXX\xaa\x02\n" +
	"Product.V1\xca\x02\n" +
	"Product\\V1\xe2\x02\x16Product\\V1\\GPBMetadata\xea\x02\vProduct::V1b\x06proto3"

var (
	file_product_v1_product_service_proto_rawDescOnce sync.Once
	file_product_v1_product_service_proto_rawDescData []byte
)

func file_product_v1_product_service_proto_rawDescGZIP() []byte {
	file_product_v1_product_service_proto_rawDescOnce.Do(func() {
		file_product_v1_product_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_v1_product_service_proto_rawDesc), len(file_product_v1_product_service_proto_rawDesc)))
	})
	return file_product_v1_product_service_proto_rawDescData
}

var file_product_v1_product_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_product_v1_product_service_proto_goTypes = []any{
	(*GetProductRequest)(nil),  // 0: product.v1.GetProductRequest
	(*GetProductResponse)(nil), // 1: product.v1.GetProductResponse
}
var file_product_v1_product_service_proto_depIdxs = []int32{
	0, // 0: product.v1.ProductService.GetProduct:input_type -> product.v1.GetProductRequest
	1, // 1: product.v1.ProductService.GetProduct:output_type -> product.v1.GetProductResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_product_v1_product_service_proto_init() }
func file_product_v1_product_service_proto_init() {
	if File_product_v1_product_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_v1_product_service_proto_rawDesc), len(file_product_v1_product_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_v1_product_service_proto_goTypes,
		DependencyIndexes: file_product_v1_product_service_proto_depIdxs,
		MessageInfos:      file_product_v1_product_service_proto_msgTypes,
	}.Build()
	File_product_v1_product_service_proto = out.File
	file_product_v1_product_service_proto_goTypes = nil
	file_product_v1_product_service_proto_depIdxs = nil
}
