// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file product/v1/product_service.proto (package product.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file product/v1/product_service.proto.
 */
export const file_product_v1_product_service: GenFile = /*@__PURE__*/
  fileDesc("CiBwcm9kdWN0L3YxL3Byb2R1Y3Rfc2VydmljZS5wcm90bxIKcHJvZHVjdC52MSIqChFHZXRQcm9kdWN0UmVxdWVzdBIVCgJpZBgBIAEoCUIJukgGcgQQAhgyIi4KEkdldFByb2R1Y3RSZXNwb25zZRIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJMl0KDlByb2R1Y3RTZXJ2aWNlEksKCkdldFByb2R1Y3QSHS5wcm9kdWN0LnYxLkdldFByb2R1Y3RSZXF1ZXN0Gh4ucHJvZHVjdC52MS5HZXRQcm9kdWN0UmVzcG9uc2VCuAEKDmNvbS5wcm9kdWN0LnYxQhNQcm9kdWN0U2VydmljZVByb3RvUAFaSGdpdGh1Yi5jb20vQ2hyaXN0aWFuR2FlcnRuZXIvY29ubmVjdC1ycGMtZGVtby9wcm90by9wcm9kdWN0L3YxO3Byb2R1Y3R2MaICA1BYWKoCClByb2R1Y3QuVjHKAgpQcm9kdWN0XFYx4gIWUHJvZHVjdFxWMVxHUEJNZXRhZGF0YeoCC1Byb2R1Y3Q6OlYxYgZwcm90bzM", [file_buf_validate_validate, file_google_protobuf_timestamp]);

/**
 * @generated from message product.v1.GetProductRequest
 */
export type GetProductRequest = Message<"product.v1.GetProductRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message product.v1.GetProductRequest.
 * Use `create(GetProductRequestSchema)` to create a new message.
 */
export const GetProductRequestSchema: GenMessage<GetProductRequest> = /*@__PURE__*/
  messageDesc(file_product_v1_product_service, 0);

/**
 * @generated from message product.v1.GetProductResponse
 */
export type GetProductResponse = Message<"product.v1.GetProductResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message product.v1.GetProductResponse.
 * Use `create(GetProductResponseSchema)` to create a new message.
 */
export const GetProductResponseSchema: GenMessage<GetProductResponse> = /*@__PURE__*/
  messageDesc(file_product_v1_product_service, 1);

/**
 * @generated from service product.v1.ProductService
 */
export const ProductService: GenService<{
  /**
   * @generated from rpc product.v1.ProductService.GetProduct
   */
  getProduct: {
    methodKind: "unary";
    input: typeof GetProductRequestSchema;
    output: typeof GetProductResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_product_v1_product_service, 0);

